export const ZONA_NIC_LOCALITIES = [
  "ALLEN",
  "BARILOCHE",
  "CENTENARIO",
  "CHOELE CHOEL",
  "CINCO SALTOS",
  "CIPOLLETTI",
  "CUTRAL CO",
  "GENERAL ROCA",
  "MAQUINCHAO",
  "NEUQUEN",
  "PLAZA HUINCUL",
  "PLOTTIER",
  "SAN MARTIN DE LOS ANDES",
  "SAN MARTIN DE ANDES",
  "VILLA REGINA",
  "VILLA LA ANGOSTURA",
  "VILLA LANGOSTURA",
  "ZAPALA",
] as const;

export const ZONA_NIC_LOCALITIES_SET = new Set(ZONA_NIC_LOCALITIES);
