version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: intranic_backend
    restart: always
    ports:
      - "4002:4002"
    environment:
      DATABASE_MONGO: ${DATABASE_MONGO}
      PORT: 4002
    networks:
      - intranic_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: intranic_frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - intranic_network

networks:
  intranic_network: