export const paths = {
  home: "/",
  login: "/login",
  noAutorizado: "/no-autorizado",
  stockPublico: "/stock-publico",
  admin: {
    usuarios: "/admin/usuarios",
    crearUsuario: "/admin/usuarios/crear",
    editarUsuario: (idUsuario: string) => `/admin/usuarios/${idUsuario}/editar`,
    configuracion: "/admin/configuracion",
    configuracionConvencionalEditar: "/admin/configuracion/convencional/editar",
    configuracionUsadosEditar: "/admin/configuracion/usados/editar",
    configuracionReventaEditar: "/admin/configuracion/reventa/editar",
  },
  administracion: {
    home: "/administracion",
    reventaPendientes: "/administracion/reventa-pendientes",
    pedidoUnidadesListaPrevia: "/administracion/pedido-unidades/lista-previa",
    facturasAnticipo: "/administracion/facturas-anticipo",
  },
  analisis: {
    operaciones: "/operaciones",
    patentamientos: {
      home: "/analisis/patentamientos",
      importar: "/analisis/patentamientos/importar",
      dashboard: "/analisis/patentamientos/dashboard",
      dashboardGeneral: "/analisis/patentamientos/dashboard/general",
      dashboardMarcas: "/analisis/patentamientos/dashboard/marcas",
      dashboardPickup: "/analisis/patentamientos/dashboard/pickup",
      dashboardSuv: "/analisis/patentamientos/dashboard/suv",
      dashboardBSuv: "/analisis/patentamientos/dashboard/b-suv",
      dashboardInscripcionUnidades: "/analisis/patentamientos/dashboard/inscripcion-unidades",
      dashboardSection: (section: string) => `/analisis/patentamientos/dashboard/${section}`,
    },
  },
  convencional: {
    stockDisponible: "/convencional/stock/disponible",
    stockReservado: "/convencional/stock/reservado",
    stockGuardado: "/convencional/stock/guardado",
    ranking: "/convencional/ranking-convencional",
    promedio: "/convencional/promedio-convencional",
    asignaciones: "/convencional/asignaciones",
    registroAsignaciones: "/convencional/registro-asignaciones",
    registroAsignacionesResumen: "/convencional/registro-asignaciones/resumen",
    preventas: "/convencional/preventas",
    preventasResumen: "/convencional/preventas/resumen",
    preventasAsignadas: "/convencional/preventas/asignadas",
    preventasNueva: "/convencional/preventas/nueva",
    preventasEditar: (id: string) => `/convencional/preventas/${id}/editar`,
    proformas: "/convencional/proformas",
    proformasNueva: "/convencional/proformas/nueva",
    proformasDetalle: (id: string) => `/convencional/proformas/${id}`,
    pedidoMensual: "/convencional/pedido-mensual",
    pedidoUnidades: "/convencional/pedido-unidades",
    preventasColores: "/convencional/preventas/colores",
    preventasColoresNuevo: "/convencional/preventas/colores/nuevo",
    preventasColoresEditar: (id: string) => `/convencional/preventas/colores/${id}/editar`,
    preventasVersiones: "/convencional/preventas/versiones",
    preventasVersionesNuevo: "/convencional/preventas/versiones/nuevo",
    preventasVersionesEditar: (id: string) => `/convencional/preventas/versiones/${id}/editar`,
    miPerfil: "/convencional/mi-perfil",
    misReservas: "/convencional/mis-reservas",
    miListaEspera: "/convencional/mi-lista-espera",
    misOperaciones: "/convencional/mis-operaciones",
  },
  usados: {
    stockDisponible: "/usados/stock/disponible",
    stockGuardado: "/usados/stock/guardado",
    stockNoReparado: "/usados/stock/no-reparado",
    stockPendienteDocumentacion: "/usados/stock/pendiente-documentacion",
    stockReservado: "/usados/stock/reservado",
    stockIngresos: "/usados/stock/ingresos",
    misReservas: "/usados/mis-reservas",
  },
  liess: {
    miPerfil: "/mi-perfil/liess",
    stockDisponible: (tipo: string) => `/stock/disponible/liess/${tipo}`,
  },
};
