export const paths = {
  home: "/",
  login: "/login",
  notFound: "/404",
  miPerfil: "/mi-perfil",
  noAutorizado: "/no-autorizado",
  calidad: {
    home: "/calidad",
    ssiVentas: "/calidad/ssi-ventas",
  },
  entregas: {
    agenda: "/entregas/agenda",
    pendientesTurnar: "/entregas/pendientes-turnar",
    sucursales: "/entregas/sucursales",
    registros: "/entregas/registros",
  },
  admin: {
    usuarios: "/sistema/usuarios",
    crearUsuario: "/sistema/usuarios/crear",
    editarUsuarioRoute: "/sistema/usuarios/:idUsuario/editar",
    editarUsuario: (idUsuario: string) => `/sistema/usuarios/${idUsuario}/editar`,
    configuracion: "/sistema/configuracion",
    unidadesNegocio: "/sistema/configuracion/unidades-negocio",
    configuracionEnvioAgenda: "/sistema/configuracion/envio-agenda",
    configuracionHotAlert: "/sistema/configuracion/hot-alert",
    configuracionConvencionalEditar: "/sistema/configuracion/convencional/editar",
    configuracionUsadosEditar: "/sistema/configuracion/usados/editar",
    configuracionBelgranoEditar: "/sistema/configuracion/belgrano/editar",
    colores: "/sistema/configuracion/colores",
    versiones: "/sistema/configuracion/versiones",
    planNegocio: "/sistema/configuracion/plan-negocio",
    pedidoMensual: "/sistema/configuracion/pedido-mensual",
    testDrive: "/sistema/test-drive",
    vendedores: "/sistema/dms/vendedores",
  },
  administracion: {
    home: "/administracion",
    reventaPendientes: "/administracion/reventa-pendientes",
    pedidoUnidadesListaPrevia: "/administracion/pedido-unidades/lista-previa",
    pedidoUnidadesRegistros: "/administracion/pedido-unidades/registros",
    facturasAnticipo: "/administracion/facturas-anticipo",
  },
  analisis: {
    operaciones: "/analisis/operaciones",
    centralDeudores: "/analisis/central-de-deudores",
    analisisOperaciones: "/analisis/operaciones-preventa",
    vendedor: "/analisis/vendedor",
    saldoOperacion: "/analisis/saldo-operacion",
    registros: "/sistema/registros",
    patentamientos: {
      home: "/analisis/patentamientos",
      dashboard: "/analisis/patentamientos/dashboard",
      dashboardGeneral: "/analisis/patentamientos/dashboard/general",
      dashboardMarcas: "/analisis/patentamientos/dashboard/marcas",
      dashboardPickup: "/analisis/patentamientos/dashboard/pickup",
      dashboardSw4: "/analisis/patentamientos/dashboard/sw4",
      dashboardCCross: "/analisis/patentamientos/dashboard/c-cross",
      dashboardYaris: "/analisis/patentamientos/dashboard/yaris",
      dashboardYCross: "/analisis/patentamientos/dashboard/y-cross",
      dashboardLocalidad: "/analisis/patentamientos/dashboard/localidad",
      dashboardSuv: "/analisis/patentamientos/dashboard/suv",
      dashboardBSuv: "/analisis/patentamientos/dashboard/b-suv",
      dashboardInscripcionUnidades: "/analisis/patentamientos/dashboard/inscripcion-unidades",
      dashboardSectionRoute: "/analisis/patentamientos/dashboard/:section",
      dashboardSection: (section: string) => `/analisis/patentamientos/dashboard/${section}`,
    },
    transferencias: {
      home: "/analisis/transferencias",
      dashboard: "/analisis/transferencias/dashboard",
      dashboardGeneral: "/analisis/transferencias/dashboard/general",
      dashboardSectionRoute: "/analisis/transferencias/dashboard/:section",
      dashboardSection: (section: string) => `/analisis/transferencias/dashboard/${section}`,
    },
  },
  convencional: {
    stockDisponible: "/stock/convencional/disponible",
    stockReservado: "/stock/convencional/reservado",
    stockGuardado: "/stock/convencional/guardado",
    stockValorizacion: "/stock/convencional/valorizacion",
    stockValorizacionListaPrecios: "/stock/convencional/valorizacion/lista-precios",
    ranking: "/analisis/ranking-convencional",
    promedio: "/analisis/promedio-convencional",
    asignaciones: "/gestion/convencional/asignaciones",
    planNegocio: "/gestion/convencional/plan-negocio",
    registroAsignaciones: "/gestion/convencional/registro-asignaciones",
    registroAsignacionesResumen: "/gestion/convencional/registro-asignaciones/resumen",
    analisisStock: "/gestion/convencional/analisis-stock",
    analisisStockDiccionarioVersiones: "/gestion/convencional/analisis-stock/diccionario-versiones",
    pendFac: "/gestion/convencional/pend-fac",
    preventas: "/comercial/preventas",
    preventasResumen: "/comercial/preventas/resumen",
    preventasAsignadas: "/comercial/preventas/asignadas",
    preventasNueva: "/comercial/preventas/nueva",
    preventasEditarRoute: "/comercial/preventas/:id/editar",
    preventasEditar: (id: string) => `/comercial/preventas/${id}/editar`,
    proformas: "/comercial/proformas",
    proformasNueva: "/comercial/proformas/nueva",
    proformasDetalleRoute: "/comercial/proformas/:id",
    proformasDetalle: (id: string) => `/comercial/proformas/${id}`,
    minutas: "/comercial/minutas",
    minutasNueva: "/comercial/minutas/nueva",
    minutasEditarRoute: "/comercial/minutas/:id/editar",
    minutasEditar: (id: string) => `/comercial/minutas/${id}/editar`,
    pedidoMensual: "/gestion/convencional/pedido-mensual",
    pedidoUnidades: "/gestion/convencional/pedido-unidades",
    preventasColores: "/convencional/preventas/colores",
    preventasColoresNuevo: "/convencional/preventas/colores/nuevo",
    preventasColoresEditarRoute: "/convencional/preventas/colores/:id/editar",
    preventasColoresEditar: (id: string) => `/convencional/preventas/colores/${id}/editar`,
    preventasVersiones: "/convencional/preventas/versiones",
    preventasVersionesNuevo: "/convencional/preventas/versiones/nuevo",
    preventasVersionesEditarRoute: "/convencional/preventas/versiones/:id/editar",
    preventasVersionesEditar: (id: string) => `/convencional/preventas/versiones/${id}/editar`,
    misReservas: "/stock/convencional/mis-reservas",
    miListaEspera: "/stock/convencional/mi-lista-espera",
    misOperaciones: "/stock/convencional/mis-operaciones",
    registroTestDrive: "/comercial/test-drive",
    registroTestDriveCalendario: "/comercial/test-drive/calendario",
  },
  planAhorro: {
    registroTestDrive: "/plan-ahorro/test-drive",
    registroTestDriveCalendario: "/plan-ahorro/test-drive/calendario",
    promedios: "/plan-ahorro/promedios",
  },
  usados: {
    stockDisponible: "/stock/usados/disponible",
    stockGuardado: "/stock/usados/guardado",
    stockNoReparado: "/gestion/usados/stock/no-reparado",
    stockPendienteDocumentacion: "/gestion/usados/stock/pendiente-documentacion",
    stockReservado: "/stock/usados/reservado",
    stockIngresos: "/gestion/usados/stock/ingresos",
    misReservas: "/stock/usados/mis-reservas",
    misOperaciones: "/stock/usados/mis-operaciones",
  },
  belgrano: {
    stockDisponible: "/stock/belgrano/disponible",
  },
  liess: {
    stockDisponibleRoute: "/stock/liess/:tipo",
    stockDisponible: (tipo: string) => `/stock/liess/${tipo}`,
  },
};
