import { Combobox, ComboboxInput, ComboboxOption, ComboboxOptions } from "@headlessui/react";
import Loading from "@/components/Loading";
import { ActionButton, EditActionButton } from "@/components/ui/action-button";
import { getColores, getVersiones } from "@/api/dms/preventasAPI";
import { createSolicitudCambioColor, getSolicitudesCambioColor, getUnidadCambioColor, getVendedoresSolicitudCambioColor, rejectSolicitudCambioColor, updateSolicitudCambioColor, updateSolicitudCambioColorEstado } from "@/api/convencional/solicitudCambioColorAPI";
import { hasSolicitudCambioColorEstadoAccess } from "@/helpers/access";
import { textToColor } from "@/helpers/colores";
import { useAuth } from "@/hooks/useAuthe";
import type { Catalogo, SolicitudCambioColor, Vendedor } from "@/types/index";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle as AlertTriangleIcon, CircleX, History, Pencil, Plus, Search, X } from "lucide-react";
import { useMemo, useState, type ComponentProps } from "react";
import { toast } from "sonner";

type Estado = "" | "pendientes" | "pedidas" | "completadas" | "rechazadas";
const estados: Array<[Exclude<Estado, "">, string]> = [["pendientes", "Pendientes"], ["pedidas", "Pedidas"], ["completadas", "Completadas"], ["rechazadas", "Rechazadas"]];
const fecha = (value: string) => new Date(value).toLocaleString("es-AR", { dateStyle: "short", timeStyle: "short" });
const auditLabels: Record<string, string> = { created: "Solicitud creada", destinationUpdated: "Destino actualizado", requestedChanged: "Solicitud pedida actualizada", completedChanged: "Solicitud completada actualizada", rejected: "Solicitud rechazada" };
let activeAudit: SolicitudCambioColor["audit"] = [];
const AlertTriangle = ({ title, ...props }: ComponentProps<typeof AlertTriangleIcon> & { title?: string }) => { void title; return <AlertTriangleIcon {...props} />; };
const Color = ({ name }: { name: string }) => <span className={`inline-flex rounded-md border border-border px-2 py-0.5 text-xs ${textToColor(name)}`}>{name}</span>;

function AuditValues({ title, values }: { title: string; values: Record<string, unknown> }) { const entries = Object.entries(values); if (!entries.length) return null; return <div className="mt-2"><p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">{title}</p><dl className="mt-1 grid gap-1 sm:grid-cols-2">{entries.map(([key, value]) => <div key={key} className="grid grid-cols-[10rem_minmax(0,1fr)] gap-2 text-xs"><dt className="font-medium text-muted-foreground">{key}</dt><dd className="break-words text-foreground">{String(value)}</dd></div>)}</dl></div>; }
function Modal({ children, close }: { children: React.ReactNode; close: () => void }) { const content = activeAudit.length ? <div className="divide-y divide-border p-4">{[...activeAudit].reverse().map((entry) => <article key={entry._id} className="py-2 first:pt-0"><p className="text-sm font-semibold">{auditLabels[entry.action]}</p><p className="text-xs text-muted-foreground">{entry.actorName} · {fecha(entry.createdAt)}</p><AuditValues title="Valores anteriores" values={entry.before} /><AuditValues title="Valores nuevos" values={entry.after} /></article>)}</div> : children; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/30 p-3"><section className={`flex max-h-[calc(100vh-1.5rem)] w-full flex-col ${activeAudit.length ? "max-w-5xl" : "max-w-2xl"} rounded-md border border-border bg-popover`}><header className="shrink-0 flex justify-end border-b border-border p-2"><button onClick={close}><X size={18} /></button></header><div className="min-h-0 overflow-y-auto">{content}</div></section></div>; }
function VendorBox({ value, onChange, vendors }: { value: Vendedor | null; onChange: (item: Vendedor | null) => void; vendors: Vendedor[] }) { const [query, setQuery] = useState(""); const normalizedQuery = query.trim(); const visible = normalizedQuery.length >= 3 ? vendors.filter((v) => v.vendedor.toLowerCase().includes(normalizedQuery.toLowerCase())) : []; return <Combobox value={value} onChange={onChange} onClose={() => setQuery("")}><ComboboxInput aria-label="Solicitado por" displayValue={(v: Vendedor | null) => v?.vendedor ?? ""} onChange={(e) => setQuery(e.target.value)} placeholder="Ingresá al menos 3 caracteres" className="mt-1 h-9 w-full rounded-md border border-input bg-background px-3" /><ComboboxOptions anchor="bottom" className="z-[60] max-h-56 w-[var(--input-width)] overflow-auto rounded-md border border-border bg-popover p-1 shadow-lg">{normalizedQuery.length < 3 ? <p className="px-2 py-1.5 text-xs text-muted-foreground">Ingresá al menos 3 caracteres.</p> : visible.length ? visible.map((v) => <ComboboxOption key={v.codigo} value={v} className="cursor-pointer rounded px-2 py-1.5 text-sm data-focus:bg-muted data-selected:bg-secondary">{v.vendedor}</ComboboxOption>) : <p className="px-2 py-1.5 text-xs text-muted-foreground">No se encontraron vendedores.</p>}</ComboboxOptions></Combobox>; }

function Form({ item, versions, colors, vendors, close }: { item: SolicitudCambioColor | null; versions: Catalogo[]; colors: Catalogo[]; vendors: Vendedor[]; close: () => void }) {
  const qc = useQueryClient(); const [interno, setInterno] = useState(item ? String(item.interno) : ""); const [unit, setUnit] = useState<{ interno: number; version: string; color: string } | null>(item ? { interno: item.interno, version: item.versionOrigen, color: item.colorOrigen } : null); const [version, setVersion] = useState(item?.versionDestino._id ?? ""); const [color, setColor] = useState(item?.colorDestino._id ?? ""); const [color2, setColor2] = useState(item?.colorDestino2?._id ?? ""); const [obs, setObs] = useState(item?.observaciones ?? ""); const [seller, setSeller] = useState<Vendedor | null>(item ? { codigo: item.solicitadoPor.codigo, vendedor: item.solicitadoPor.nombre, tpoNuevo: true, tipoUsado: false, tipoPlan: false, tipoPosventa: false, emailTecnom: "", estado: 1, sucursal: "" } : null);
  const lookup = useMutation({ mutationFn: () => getUnidadCambioColor(Number(interno)), onSuccess: ({ data }) => setUnit(data), onError: (e: Error) => toast.error(e.message) }); const save = useMutation({ mutationFn: () => item ? updateSolicitudCambioColor(item._id, { versionDestinoId: version, colorDestinoId: color, colorDestino2Id: color2, observaciones: obs }) : createSolicitudCambioColor({ interno: Number(interno), solicitadoPorCodigo: seller!.codigo, versionDestinoId: version, colorDestinoId: color, colorDestino2Id: color2, observaciones: obs }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["solicitudes-cambio-color"] }); close(); }, onError: (e: Error) => toast.error(e.message) }); const submit = () => { if (!unit || !version || !color || (!item && !seller)) return toast.error("Completa interno, solicitado por, versión y color"); save.mutate(); };
  return <Modal close={close}><div className="space-y-3 p-4"><h2 className="text-lg font-semibold">{item ? "Editar solicitud" : "Nueva solicitud"}</h2><div className="grid gap-2 md:grid-cols-[1fr_auto]"><label>Interno<input disabled={!!item} value={interno} onChange={(e) => setInterno(e.target.value)} className="mt-1 h-9 w-full rounded-md border border-input px-3" /></label>{!item && <ActionButton className="self-end" onClick={() => lookup.mutate()}><Search />Consultar</ActionButton>}</div>{unit && <p className="border-y border-border py-2 text-sm">{unit.interno} · {unit.version} · <Color name={unit.color} /></p>}<div className="grid gap-3 sm:grid-cols-2">{!item && <label>Solicitado por<VendorBox value={seller} onChange={setSeller} vendors={vendors} /></label>}<label>Versión destino<Select value={version} set={setVersion} items={versions} placeholder="Seleccionar versión" /></label><label>Color destino<Select value={color} set={setColor} items={colors} placeholder="Seleccionar color" /></label><label>Segundo color<Select value={color2} set={setColor2} items={colors.filter((x) => x._id !== color)} placeholder="Sin segundo color" /></label><label>Observaciones / N° OP.<textarea value={obs} onChange={(e) => setObs(e.target.value)} className="mt-1 w-full rounded-md border border-input p-2" /></label></div></div><footer className="flex justify-end gap-2 border-t border-border p-3"><EditActionButton onClick={close}>Cancelar</EditActionButton><ActionButton onClick={submit}>Guardar</ActionButton></footer></Modal>;
}
function Select({ value, set, items, placeholder }: { value: string; set: (v: string) => void; items: Catalogo[]; placeholder: string }) { return <select value={value} onChange={(e) => set(e.target.value)} className="mt-1 h-9 w-full rounded-md border border-input px-3"><option value="">{placeholder}</option>{items.map((x) => <option key={x._id} value={x._id}>{x.nombre}</option>)}</select>; }

export default function SolicitudCambioColorView() {
  const qc = useQueryClient(); const { user } = useAuth(); const canManage = hasSolicitudCambioColorEstadoAccess(user); const [estado, setEstado] = useState<Estado>("pendientes"); const [interno, setInterno] = useState(""); const [form, setForm] = useState<SolicitudCambioColor | null | undefined>(); const [history, setHistory] = useState<SolicitudCambioColor | null>(null); const params = useMemo(() => ({ ...(estado ? { estado } : {}), ...(interno ? { interno } : {}) }), [estado, interno]); const list = useQuery({ queryKey: ["solicitudes-cambio-color", params], queryFn: () => getSolicitudesCambioColor(params) }); const versions = useQuery({ queryKey: ["versiones", "activas"], queryFn: () => getVersiones(true) }); const colors = useQuery({ queryKey: ["colores", "activos"], queryFn: () => getColores(true) }); const vendors = useQuery({ queryKey: ["solicitudes-cambio-color", "vendedores"], queryFn: getVendedoresSolicitudCambioColor });
  activeAudit = history?.audit ?? [];
  const change = useMutation({ mutationFn: ({ id, field, value }: { id: string; field: "solicitudPedida" | "solicitudCompletada"; value: boolean }) => updateSolicitudCambioColorEstado(id, field, value), onSuccess: () => qc.invalidateQueries({ queryKey: ["solicitudes-cambio-color"] }) }); const reject = useMutation({ mutationFn: rejectSolicitudCambioColor, onSuccess: () => qc.invalidateQueries({ queryKey: ["solicitudes-cambio-color"] }) }); if (list.isLoading || versions.isLoading || colors.isLoading || vendors.isLoading) return <Loading />; const rows = list.data?.data ?? [];
  return <div className="font-preset space-y-3 bg-muted p-3"><section className="border border-border bg-card p-3"><div className="flex justify-between"><div><h1 className="text-xl font-semibold">Solicitudes de cambio de color</h1><p className="text-sm text-muted-foreground">Gestión de unidades 0 km.</p></div><ActionButton onClick={() => setForm(null)}><Plus />Nueva solicitud</ActionButton></div><div className="mt-3 grid grid-cols-2 gap-1 md:grid-cols-4">{estados.map(([v, l]) => <button key={v} onClick={() => setEstado(v)} className={`h-9 rounded-md border text-xs ${estado === v ? "bg-primary text-primary-foreground" : "bg-card"}`}>{l}</button>)}</div></section><section className="overflow-hidden border border-border bg-card"><div className="flex justify-end border-b border-border p-3"><input value={interno} onChange={(e) => setInterno(e.target.value)} placeholder="Filtrar por interno" className="h-9 rounded-md border border-input px-3" /></div><div className="overflow-x-auto"><table className="min-w-[1250px] w-full text-sm"><thead className="bg-muted text-xs uppercase"><tr><th>Interno</th><th>Origen</th><th>Destino</th><th>N° OP.</th><th>Solicitado por</th><th>Pedida</th><th>Completada</th><th>Acciones</th></tr></thead><tbody>{rows.map((x) => <tr key={x._id} className="border-t border-border"><td className="p-2 font-semibold">{x.interno}{x.tieneChasis && <AlertTriangle className="ml-1 inline text-destructive" size={16} title="La unidad ya tiene chasis" />}</td><td><p>{x.versionOrigen}</p><Color name={x.colorOrigen} /></td><td><p>{x.versionDestino.nombre}</p><Color name={x.colorDestino.nombre} />{x.colorDestino2 && <Color name={x.colorDestino2.nombre} />}</td><td>{x.observaciones || "-"}</td><td>{x.solicitadoPor.nombre}</td><td><input type="checkbox" checked={x.solicitudPedida} disabled={!canManage || x.solicitudRechazada} onChange={(e) => change.mutate({ id: x._id, field: "solicitudPedida", value: e.target.checked })} /></td><td><input type="checkbox" checked={x.solicitudCompletada} disabled={!canManage || !x.solicitudPedida || x.solicitudRechazada} onChange={(e) => change.mutate({ id: x._id, field: "solicitudCompletada", value: e.target.checked })} /></td><td><EditActionButton onClick={() => setForm(x)} disabled={x.solicitudRechazada}><Pencil />Editar</EditActionButton><EditActionButton onClick={() => setHistory(x)}><History />Historial</EditActionButton>{canManage && !x.solicitudCompletada && !x.solicitudRechazada && <ActionButton variant="destructive" onClick={() => reject.mutate(x._id)}><CircleX />Rechazar</ActionButton>}</td></tr>)}</tbody></table></div></section>{form !== undefined && <Form item={form} versions={versions.data?.data ?? []} colors={colors.data?.data ?? []} vendors={vendors.data?.data ?? []} close={() => setForm(undefined)} />}{history && <Modal close={() => setHistory(null)}><div className="p-4">{history.audit.map((a) => <p key={a._id}>{a.actorName} · {fecha(a.createdAt)}</p>)}</div></Modal>}</div>;
}
